<?php
declare(strict_types=1);

/**
 * PSA e-payment standard (EPS) implementation for PHP
 *
 * Copyright 2026 PSA Payment Services Austria GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Knusperleicht\EpsBankTransfer\Responses;

use Knusperleicht\EpsBankTransfer\Internal\Generated\Payment\V26\ShopConfirmationDetails;
use Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\EpsProtocolDetails;

/**
 * Domain model for building the shop's confirmation response to the EPS SO.
 */
class ShopResponseDetails
{
    /**
     * Build EPS v2.6 schema object from domain ShopResponseDetails.
     *
     * Returns an EpsProtocolDetails payload ready to be serialized and sent back
     * to the Scheme Operator (SO) as confirmation response.
     *
     * Rules (v2.6):
     * - When errorMessage is set, only ErrorMsg (and optional SessionId) is populated.
     * - Otherwise a ShopConfirmationDetails block with StatusCode and PaymentReferenceIdentifier is provided.
     */
    /** @var string Human-readable error message provided by the shop, if any */
    public $errorMessage;

    /** @var string Session identifier generated by the bank */
    public $sessionId;

    /** @var string Status code of the EPS transaction as returned by the bank */
    public $statusCode;

    /** @var string Bank-generated payment reference identifier */
    public $paymentReferenceIdentifier;

    /**
     * Domain to EPS schema mapping (v2.6).
     *
     * @return EpsProtocolDetails Fully populated response ready to return to SO.
     */
    public function toV26(): EpsProtocolDetails
    {
        $epsProtocolDetails = new EpsProtocolDetails();
        $shopResponseDetails = new \Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\ShopResponseDetails();

        if (!empty($this->errorMessage)) {
            $shopResponseDetails->setErrorMsg($this->errorMessage);
            if (!empty($this->sessionId)) {
                $shopResponseDetails->setSessionId($this->sessionId);
            }
        } else {
            $shopResponseDetails->setSessionId($this->sessionId);

            $shopConfirmationDetails = new ShopConfirmationDetails();
            $shopConfirmationDetails->setStatusCode($this->statusCode);
            $shopConfirmationDetails->setPaymentReferenceIdentifier($this->paymentReferenceIdentifier);
            $shopResponseDetails->setShopConfirmationDetails($shopConfirmationDetails);
        }

        $epsProtocolDetails->setShopResponseDetails($shopResponseDetails);
        return $epsProtocolDetails;
    }

    /**
     * Build EPS v2.7 schema object from domain ShopResponseDetails.
     */
    public function toV27(): \Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\EpsProtocolDetails
    {
        $epsProtocolDetails = new \Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\EpsProtocolDetails();
        $shopResponseDetails = new \Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\ShopResponseDetails();

        if (!empty($this->errorMessage)) {
            $shopResponseDetails->setErrorMsg($this->errorMessage);
            if (!empty($this->sessionId)) {
                $shopResponseDetails->setSessionId($this->sessionId);
            }
        } else {
            $shopResponseDetails->setSessionId($this->sessionId);

            $shopConfirmationDetails = new \Knusperleicht\EpsBankTransfer\Internal\Generated\Payment\V27\ShopConfirmationDetails();
            $shopConfirmationDetails->setStatusCode($this->statusCode);
            $shopConfirmationDetails->setPaymentReferenceIdentifier($this->paymentReferenceIdentifier);
            $shopResponseDetails->setShopConfirmationDetails($shopConfirmationDetails);
        }

        $epsProtocolDetails->setShopResponseDetails($shopResponseDetails);
        return $epsProtocolDetails;
    }

    /**
     * @param string $statusCode
     */
    public function setStatusCode(string $statusCode): void
    {
        $this->statusCode = $statusCode;
    }

    /**
     * @param string $sessionId
     */
    public function setSessionId(string $sessionId): void
    {
        $this->sessionId = $sessionId;
    }

    /**
     * @param string $paymentReferenceIdentifier
     */
    public function setPaymentReferenceIdentifier(string $paymentReferenceIdentifier): void
    {
        $this->paymentReferenceIdentifier = $paymentReferenceIdentifier;
    }

    /**
     * @param string $errorMessage
     */
    public function setErrorMessage(string $errorMessage): void
    {
        $this->errorMessage = $errorMessage;
    }
}